### ISSUE TITLE
Remove superfluous GitHub connector

### ISSUE THREAD

**Issue by maxhov** [Blazebit/blaze-query#32]
I see two GitHub connectors, one based on the OpenAPI spec and the other based on a custom SDK (https://github-api.kohsuke.org/). Shall we remove the custom SDK connector, since it is no longer used?

**Comment by beikov** [comment]
Fixed via https://github.com/Blazebit/blaze-query/commit/7f17376d6b0ca5cbc7464a27efa3e1a8e212caab
